apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rahulltelkardotnet 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rahulltelkardotnet 
    spec:
      containers:
        - name: rahulltelkardotnet 
          image: rahulimageregistry.azurecr.io/rahulltelkardotnet
          ports:
          - containerPort: 80